version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.DeviceDiscovery.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: Cups7ORXpNjXlmQ1ZvUmS/wiN71MtJ/Kin+31h9Z2Yt5H4kziepSpttdzmNAMAnv
  artifact: /.*\.nupkg/
